apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: deployment.deployment-10-3-4
    app.kubernetes.io/instance: app-10-3
    app.kubernetes.io/name: app-10-3
  name: deployment-10-3-4
  namespace: ns-10
spec:
  replicas: 3 
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment.deployment-10-3-4
      app.kubernetes.io/instance: app-10-3
      app.kubernetes.io/name: app-10-3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: deployment.deployment-10-3-4
        app.kubernetes.io/instance: app-10-3
        app.kubernetes.io/name: app-10-3
    spec:
      containers:
      - env:
        - name: env1
          value: value1
        - name: env2
          value: value2
        - name: env3
          value: value3
        name: fake-container
        image: fake-image
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 64Mi
      volumes:
      - emptyDir: {}
        name: empty-dir-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - kwok
      # A taints was added to an automatically created Node.
      # You can remove taints of Node or add this tolerations.
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
