name: Mirmata Load Tests

on:
  workflow_dispatch:

env:
  NIRMATA_URL: nirmata.io
  NIRMATA_NPM_ADMIN_TOKEN: ${{ secrets.NPM_ADMIN_TOKEN }}
  NIRMATA_NPM_DEVOPS_TOKEN: ${{ secrets.NPM_DEVOPS_TOKEN }}
  NIRMATA_NDP_ADMIN_TOKEN: ${{ secrets.NDP_ADMIN_TOKEN }}
  NIRMATA_NDP_DEVOPS_TOKEN: ${{ secrets.NDP_DEVOPS_TOKEN }}
  K6_VUS: 10
  K6_DURATION: 15s

jobs:
  k6_load_test:
    name: Nirmata K6 Load Tests
    runs-on: ubuntu-latest
    steps:
    - name: set addititonal environment variables
      run: |
         echo "K6_NPM_ADMIN_FLAGS= --env NIRMATA_API_TOKEN=$NIRMATA_NPM_ADMIN_TOKEN --vus $K6_VUS --duration $K6_DURATION" >> $GITHUB_ENV
         echo "K6_NPM_DEVOPS_FLAGS= --env NIRMATA_API_TOKEN=$NIRMATA_NPM_DEVOPS_TOKEN --vus $K6_VUS --duration $K6_DURATION" >> $GITHUB_ENV
         echo "K6_NDP_ADMIN_FLAGS= --env NIRMATA_API_TOKEN=$NIRMATA_NDP_ADMIN_TOKEN --vus $K6_VUS --duration $K6_DURATION" >> $GITHUB_ENV
         echo "K6_NDP_DEVOPS_FLAGS= --env NIRMATA_API_TOKEN=$NIRMATA_NDP_DEVOPS_TOKEN --vus $K6_VUS --duration $K6_DURATION" >> $GITHUB_ENV
         
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: policy-reports-admin
      uses: grafana/k6-action@v0.2.0
      with:
        filename: ./tests/npm/policy-reports-test.js
        flags: $K6_NPM_ADMIN_FLAGS
        
    - name: policy-report-admin
      uses: grafana/k6-action@v0.2.0
      with:
        filename: ./tests/npm/policy-report-test.js
        flags: $K6_NPM_ADMIN_FLAGS

